name: Deploy to Production Server
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update and Start EKN
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.PROD_HOST}}
          username: ${{secrets.PROD_USERNAME}}
          password: ${{secrets.PROD_PASSWORD}}
          port: ${{secrets.PROD_PORT}}
          script: |
            source /home/etn/venv/bin/activate
            python3 /home/etn/service_stop.py
            git --git-dir=/home/etn/ETN/.git --work-tree=/home/etn/ETN pull origin master --rebase
            python3 /home/etn/service_start.py
            deactivate
